# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: CA IV
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Playing with Jekyll
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://agtlucas.github.io" # the base hostname & protocol for your site
twitter_username: _agtlucas
github_username:  AgtLucas

# Build settings
markdown: kramdown
